#!/usr/bin/env bash
#
# build_arch.sh — Build NovaUnlock-v${VERSION:-2.21}-Arch.pkg.tar.zst
# makepkg is unavailable, so the package is constructed manually:
#   .PKGINFO + .MTREE (via gen_mtree.py) + .INSTALL + file tree, then tar --zstd.
# Pyc compiled with host python3.13 (matches Arch rolling 3.13).
#
set -euo pipefail

VERSION="3.2"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RELEASE="$REPO/build/release"
OUT="$RELEASE/NovaUnlock-v$VERSION-Arch.pkg.tar.zst"

PY_BIN="python3.13"
WORK="$(mktemp -d)"
STAGE="$WORK/root"

command -v zstd >/dev/null 2>&1 || { echo "!! zstd required (apt install zstd)"; exit 1; }

echo "==> Staging pyc tree (python $PY_BIN)"
bash "$REPO/scripts/build_pkg_tree.sh" "$PY_BIN" "$STAGE"

# Static integration files
mkdir -p "$STAGE/usr/lib/systemd/user" "$STAGE/usr/lib/systemd/system" "$STAGE/etc/xdg/autostart"
install -m 0644 "$REPO/systemd/nova-facelock.service" \
    "$STAGE/usr/lib/systemd/system/nova-facelock.service"
cat > "$STAGE/usr/lib/systemd/user/nova-unlock-watcher.service" << 'UNIT'
[Unit]
Description=NovaUnlock Face Presence Guard
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/bin/bash -c '/usr/bin/python3 /opt/novaunlock/scripts/face_unlock_daemon.pyc --guard'
Restart=on-failure
RestartSec=5
Environment=DISPLAY=:0
Environment=NOVA_FACES_DIR=/var/lib/novaunlock/faces

[Install]
WantedBy=graphical-session.target
UNIT

cat > "$STAGE/etc/xdg/autostart/nova-unlock-watcher.desktop" << 'DESK'
[Desktop Entry]
Type=Application
Name=NovaUnlock Watcher
Exec=/usr/local/bin/nova_unlock_watcher.sh
Comment=NovaUnlock face authentication watcher
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
X-KDE-autostart-after=panel
DESK

# Arch install script
cat > "$STAGE/.INSTALL" << 'INSTALL'
post_install() {
    # The shared postinstall (ensure_runtime_deps) pip-installs dlib / face_recognition
    # into the SYSTEM site-packages. Do NOT install into the per-user site-packages
    # (PEP 370: uid 0 ignores user-site), or the daemon could never import them.
    [ -x /opt/novaunlock/nova_pkg_postinstall.sh ] && /opt/novaunlock/nova_pkg_postinstall.sh configure || true
}
pre_remove() {
    [ -x /opt/novaunlock/nova_pkg_postinstall.sh ] && /opt/novaunlock/nova_pkg_postinstall.sh remove || true
}
post_remove() {
    rm -rf /opt/novaunlock
    rm -f /var/lib/novaunlock/pam_cache.json
    rm -rf /var/log/novaunlock
}
INSTALL

# .PKGINFO
SIZE=$(find "$STAGE" -type f -not -name '.PKGINFO' -not -name '.MTREE' -not -name '.INSTALL' -printf '%s\n' | awk '{s+=$1} END{print s}')
BUILDATE="$(date +%s)"
cat > "$STAGE/.PKGINFO" << PKG
# Generated by NovaUnlock manual build
pkgname = novaunlock
pkgver = ${VERSION}-1
pkgdesc = Next-generation face authentication for Linux (commercial, 30-day trial)
url = https://github.com/hananqaisar-commits/NovaUnlock
builddate = ${BUILDATE}
packager = Hanan Qaisar <hananqaisar316@gmail.com>
size = ${SIZE}
arch = x86_64
license = custom
depend = python
depend = python-pip
depend = python-pyqt5
depend = python-opencv
depend = python-numpy
depend = python-yaml
depend = python-xlib
depend = pam
PKG

# .MTREE (excludes the three metadata files)
"$PY_BIN" "$REPO/scripts/gen_mtree.py" "$STAGE" "$STAGE/.MTREE"

# Build the archive: metadata first, then the tree
echo "==> Creating $OUT"
tar --zstd -cf "$OUT" -C "$STAGE" .PKGINFO .MTREE .INSTALL \
    opt usr etc
sha256sum "$OUT" > "$OUT.sha256"
echo "==> Built: $OUT ($(stat -c %s "$OUT") bytes)"

rm -rf "$WORK"
echo "==> Done."
